version: "3"
services:
  zk-1:
    container_name: "zk-1"
    image: confluentinc/cp-zookeeper:5.1.2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_INIT_LIMIT: "5"
      ZOOKEEPER_SYNC_LIMIT: "2"
      ZOOKEEPER_SERVERS: "0.0.0.0:2888:3888;zk-2:2888:3888;zk-3:2888:3888"

  zk-2:
    container_name: "zk-2"
    image: confluentinc/cp-zookeeper:5.1.2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_SERVER_ID: "2"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_INIT_LIMIT: "5"
      ZOOKEEPER_SYNC_LIMIT: "2"
      ZOOKEEPER_SERVERS: "zk-1:2888:3888;0.0.0.0:2888:3888;zk-3:2888:3888"

  zk-3:
    container_name: "zk-3"
    image: confluentinc/cp-zookeeper:5.1.2
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_SERVER_ID: "3"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_INIT_LIMIT: "5"
      ZOOKEEPER_SYNC_LIMIT: "2"
      ZOOKEEPER_SERVERS: "zk-1:2888:3888;zk-2:2888:3888;0.0.0.0:2888:3888"

  kafka-1:
    container_name: "kafka-1"
    image: confluentinc/cp-kafka:5.1.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_JMX_PORT: "60001"
      KAFKA_JMX_HOSTNAME: "kafka-1"
      KAFKA_ZOOKEEPER_CONNECT: "zk-1:2181,zk-2:2181,zk-3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,ADVERTISED_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # Schema-Registry looks for 'PLAINTEXT', so we must have that name
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,ADVERTISED_LISTENER://localhost:9092
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_MIN_INSYNC_REPLICAS: "2"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"

  kafka-2:
    container_name: "kafka-2"
    image: confluentinc/cp-kafka:5.1.2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: "2"
      KAFKA_JMX_PORT: "60002"
      KAFKA_JMX_HOSTNAME: "kafka-2"
      KAFKA_ZOOKEEPER_CONNECT: "zk-1:2181,zk-2:2181,zk-3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,ADVERTISED_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092,ADVERTISED_LISTENER://localhost:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_MIN_INSYNC_REPLICAS: "2"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"

  kafka-3:
    container_name: "kafka-3"
    image: confluentinc/cp-kafka:5.1.2
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: "3"
      KAFKA_JMX_PORT: "60003"
      KAFKA_JMX_HOSTNAME: "kafka-3"
      KAFKA_ZOOKEEPER_CONNECT: "zk-1:2181,zk-2:2181,zk-3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,ADVERTISED_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092,ADVERTISED_LISTENER://localhost:9094
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_MIN_INSYNC_REPLICAS: "2"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"

  kafka-manager:
    container_name: "kafka-manager"
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      KM_VERSION: "1.3.3.23"
      ZK_HOSTS: "zk-1:2181,zk-2:2181,zk-3:2181"
      APPLICATION_SECRET: "soincrediblyseecret"
      KM_ARGS: "-Dpidfile.path=/dev/null"

  schema-registry:
    container_name: "schema-registry"
    image: confluentinc/cp-schema-registry:5.1.2
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zk-1:2181,zk-2:2181,zk-3:2181"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
